import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
//import './globals.css'
import Link from 'next/link'
import Home from './page'
import Script from 'next/script'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Resume',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="nav" style={{textAlign: "left"}}>
          <Link href="/"> Home </Link>
          <Link href="/about"> About </Link>
        </nav>
        {children}
        <Script src="/java.js" strategy="afterInteractive" />
      </body>
    </html>
  )
}
