import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
//import './globals.css'
import Link from 'next/link'
import Resume1 from './resume1/page'  
import Resume2 from './resume2/page'
import Resume3 from './resume3/page'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Resume',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">

      <body className={inter.className}>
      <nav className="nav">
        <Link href="/"> Home </Link>
        <Link href="/resume1"> Resume1 </Link>
        <Link href="/resume2"> Resume2 </Link>
        <Link href="/resume3"> Resume3 </Link>
      </nav>
      {children}
      </body>
    </html>
  )
}
